# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Z0228550\OneDrive - ZF Friedrichshafen AG\Documents\Python_projects\minitab\Plot_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
#添加项
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QFont
import sys

# 

class Ui_Equation(QDialog):
    #添加初始化函数
    eq_res = pyqtSignal(str, list, int)
    def __init__(self, data = {1: [1], 2: [2, 4]}):          
        
        super(Ui_Equation,self).__init__()
        self.setupUi(self)
        self.input_Data = data
        self.inputFormula = "*1"
        self.outputcolumn = "c1"
        self.result = []
        self.select = ""
        self.row_num = 1
        ### 根据不同的图表来修改交互界面的按钮
        # if name == 'Pareto':
        #     self.pareto()

        # if name == 'Individual':
            
        #     self.Individual_p()

        # if name == 'box':
            
        #     self.box()
        ###     
        
        for key in self.input_Data.keys():
            try:
                if "*" in key:
                    self.select = key
                    continue
            except:
                pass
            self.comboBox.addItem(str(key))
        
    ### Qtdesigner生成项
    def setupUi(self, Plot_interface):
        Plot_interface.setObjectName("Plot_interface")
        Plot_interface.resize(370, 445)
        # self.listWidget = QtWidgets.QListWidget(Plot_interface)
        # self.listWidget.setGeometry(QtCore.QRect(60, 50, 191, 321))
        # self.listWidget.setObjectName("listWidget")
        # self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        # self.select_btn = QtWidgets.QPushButton(Plot_interface, text = 'Select')
        # self.select_btn.setFont(QFont('Arial', 10))
        # self.select_btn.setObjectName("select_btn")
        # self.select_btn.setGeometry(QtCore.QRect(110, 380, 75, 23))
        # self.label_4 = QtWidgets.QLabel(Plot_interface)
        # self.label_4.setGeometry(QtCore.QRect(60, 20, 121, 16))
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # self.label_4.setFont(font)
        # self.label_4.setObjectName("label_4")
        self.buttonBox = QtWidgets.QDialogButtonBox(Plot_interface)
        self.buttonBox.setGeometry(QtCore.QRect(100, 370, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(Plot_interface)
        self.label_3.setGeometry(QtCore.QRect(60, 20, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.toolBox = QtWidgets.QToolBox(Plot_interface)
        self.toolBox.setGeometry(QtCore.QRect(70, 70, 251, 261))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 251, 201))
        self.page.setObjectName("page")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.lineEdit_For1 = QtWidgets.QLineEdit(Plot_interface)
        self.lineEdit_For1.setObjectName("lineEdit_For1")
        self.gridLayout.addWidget(self.lineEdit_For1, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_out1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_out1.setFont(font)
        self.label_out1.setObjectName("label_out1")
        self.gridLayout.addWidget(self.label_out1, 5, 0, 1, 1)
        self.lineEdit_out1 = QtWidgets.QLineEdit(Plot_interface)
        self.lineEdit_out1.setObjectName("lineEdit_out1")
        self.gridLayout.addWidget(self.lineEdit_out1, 6, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 251, 201))
        self.page_2.setObjectName("page_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 211, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        ### text input2
        self.lineEdit_For2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_For2.setObjectName("lineEdit_For2")
        self.gridLayout_2.addWidget(self.lineEdit_For2, 2, 0, 1, 1)
        ###
        # self.clear_btn2 = QtWidgets.QPushButton(self.layoutWidget, text = 'Clear')
        # self.clear_btn2.setFont(QFont('Arial', 10))
        # self.clear_btn2.setObjectName("clear_btn2")
        # self.gridLayout_2.addWidget(self.clear_btn2, 3,0,1,1)
        self.toolBox.addItem(self.page_2, "")
        self.label_out2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_out2.setFont(font)
        self.label_out2.setObjectName("label_out2")
        self.gridLayout_2.addWidget(self.label_out2, 4, 0, 1, 1)
        self.lineEdit_out2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_out2.setObjectName("lineEdit_out2")
        self.gridLayout_2.addWidget(self.lineEdit_out2, 5, 0, 1, 1)

        self.retranslateUi(Plot_interface)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Plot_interface)
        
        self.buttonBox.rejected.connect(Plot_interface.reject) # type: ignore
        self.buttonBox.accepted.connect(self.cal_by_col)

    def retranslateUi(self, Plot_interface):
        _translate = QtCore.QCoreApplication.translate
        Plot_interface.setWindowTitle(_translate("Plot_interface", "Equation"))
        # self.label_4.setText(_translate("Plot_interface", "Title List:"))
        self.label_3.setText(_translate("Plot_interface", "Choose your Methods:"))
        self.label_2.setText(_translate("Plot_interface", "Input Formula:"))
        self.label.setText(_translate("Plot_interface", "Input Column:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Plot_interface", "Created by Column"))
        self.label_6.setText(_translate("Plot_interface", "Input Formula:"))
        self.label_out1.setText(_translate("Plot_interface", "Output Column:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Plot_interface", "Created by Cell"))
        self.label_out2.setText(_translate("Plot_interface", "Number of Output Cells:"))
    ###


    def clear(self):
        if self.toolBox.currentIndex() == 0:
            self.lineEdit_For1.clear()
        if self.toolBox.currentIndex() == 1:
            self.lineEdit_For2.clear()
        self.t_set = set()
        self.t_set2 = set()

    #将选中项读取到text_input
    # def printselectText(self):
    #         items = self.listWidget.selectedItems()
    #         selected_texts = [str(item.text()) for item in items]
    #         try:
    #             if self.toolBox.currentIndex() == 0:
    #                 self.text_input.setText(" ".join(selected_texts))
    #             if self.toolBox.currentIndex() == 1:
    #                 self.text_input2.setText(" ".join(selected_texts))
    #         except:
    #             pass

    def cal_by_col(self):

        if self.toolBox.currentIndex() == 1:
            self.cal_by_cell()
            return ''
        
        try:
            self.out_col = self.lineEdit_out1.text()
            self.formu = self.lineEdit_For1.text()
            input_col = self.comboBox.currentText() if self.comboBox.currentText() != '' else 1
            in_data = self.input_Data[input_col]
            
            for i in in_data:
                res = eval(str(i)+self.formu)
                self.result.append(res)
            self.eq_res.emit(self.out_col, self.result, self.row_num)
            
            self.close()

        except BaseException as e:
            error_dialog = QtWidgets.QErrorMessage()
            error_dialog.setWindowTitle("Error")
            error_dialog.showMessage(str(e))
            error_dialog.exec_()

    def cal_by_cell(self):
        if self.toolBox.currentIndex() == 0:
            self.cal_by_col()
            return ''
        try:
            self.text = self.lineEdit_out2.text()
            self.formu = self.lineEdit_For2.text()
            try:
                self.select = self.select.lstrip("*")
            except:
                self.select = "c1"
            self.out_num = int(self.lineEdit_out2.text())
            try:
                data = self.input_Data[self.select]
            except:
                data = [1]
            self.row_num = len(data)
            loop_num = data[-1] if data else 1
            self.result.append(float(loop_num))
            for i in range(self.out_num):
                res = eval(str(loop_num) + self.formu)
                loop_num = res 
                self.result.append(res)
            # print(self.result)
            self.select = "*"+self.select
            self.eq_res.emit(self.select, self.result, self.row_num)
            self.close()
        except BaseException as e:
            error_dialog = QtWidgets.QErrorMessage()
            error_dialog.setWindowTitle("Error")
            error_dialog.showMessage(str(e))
            error_dialog.exec_()

        
    def retranslateUi(self, Plot_interface):
        _translate = QtCore.QCoreApplication.translate
        Plot_interface.setWindowTitle(_translate("Plot_interface", "Equation"))
        # self.label_4.setText(_translate("Plot_interface", "Title List:"))
        self.label_3.setText(_translate("Plot_interface", "Choose your Methods:"))
        self.label_2.setText(_translate("Plot_interface", "Input Formula:"))
        self.label.setText(_translate("Plot_interface", "Input Column:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Plot_interface", "Created by Column"))
        self.label_6.setText(_translate("Plot_interface", "Input Formula:"))
        self.label_out1.setText(_translate("Plot_interface", "Output Column:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Plot_interface", "Created by Cell"))
        self.label_out2.setText(_translate("Plot_interface", "Number of Output Cells:"))
    ###


    def closeall(self):
        self.done(0)
        self.close()
        # self.canvas.close()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_Equation()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())