# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general_plot_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self,type):
        self.type=type
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(477, 243)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 10, 141, 191))
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.select_btn = QtWidgets.QPushButton(Dialog)
        self.select_btn.setGeometry(QtCore.QRect(40, 210, 75, 23))
        self.select_btn.setObjectName("select_btn")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setGeometry(QtCore.QRect(190, 200, 111, 31))
        self.ok_btn.setObjectName("ok_btn")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(340, 200, 101, 31))
        self.cancel_btn.setObjectName("cancel_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 10, 47, 13))
        self.label.setObjectName("label")
        self.text_input = QtWidgets.QTextEdit(Dialog)
        self.text_input.setGeometry(QtCore.QRect(170, 30, 301, 101))
        self.text_input.setObjectName("text_input")
        self.clear_btn = QtWidgets.QPushButton(Dialog)
        self.clear_btn.setGeometry(QtCore.QRect(400, 8, 71, 21))
        self.clear_btn.setObjectName("clear_btn")
        self.setting_btn = QtWidgets.QPushButton(Dialog)
        self.setting_btn.setGeometry(QtCore.QRect(260, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.setting_btn.setFont(font)
        self.setting_btn.setObjectName("setting_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", self.type))
        self.select_btn.setText(_translate("Dialog", "Select"))
        self.ok_btn.setText(_translate("Dialog", "OK"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Series:"))
        self.clear_btn.setText(_translate("Dialog", "Clear"))
        self.setting_btn.setText(_translate("Dialog", "Setting"))
