# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Plot_Window_Time_Series_Setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(304, 163)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.Btn_X_Sequence = QtWidgets.QRadioButton(self.groupBox_2)
        self.Btn_X_Sequence.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.Btn_X_Sequence.setChecked(True)
        self.Btn_X_Sequence.setObjectName("Btn_X_Sequence")
        self.Btn_X_Specific = QtWidgets.QRadioButton(self.groupBox_2)
        self.Btn_X_Specific.setGeometry(QtCore.QRect(10, 46, 101, 21))
        self.Btn_X_Specific.setObjectName("Btn_X_Specific")
        self.X_column = QtWidgets.QComboBox(self.groupBox_2)
        self.X_column.setGeometry(QtCore.QRect(10, 71, 101, 21))
        self.X_column.setObjectName("X_column")
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.Btn_OK = QtWidgets.QPushButton(Dialog)
        self.Btn_OK.setObjectName("Btn_OK")
        self.gridLayout_3.addWidget(self.Btn_OK, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Setting"))
        self.groupBox_2.setTitle(_translate("Dialog", "X-axis"))
        self.Btn_X_Sequence.setText(_translate("Dialog", "Sequence"))
        self.Btn_X_Specific.setText(_translate("Dialog", "Specific column"))
        self.Btn_OK.setText(_translate("Dialog", "OK"))
