# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Scatter_plot_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(290, 166)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 101, 101))
        self.groupBox.setObjectName("groupBox")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 70, 61))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.checkBox_1 = QtWidgets.QCheckBox(self.splitter)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.splitter)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.splitter)
        self.checkBox_3.setObjectName("checkBox_3")
        self.ok_Btn = QtWidgets.QPushButton(Dialog)
        self.ok_Btn.setGeometry(QtCore.QRect(110, 130, 75, 31))
        self.ok_Btn.setObjectName("ok_Btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Setting"))
        self.groupBox.setTitle(_translate("Dialog", "Fit Line"))
        self.checkBox_1.setText(_translate("Dialog", "Linear"))
        self.checkBox_2.setText(_translate("Dialog", "Quadratic"))
        self.checkBox_3.setText(_translate("Dialog", "Cubic"))
        self.ok_Btn.setText(_translate("Dialog", "OK"))
